### ISSUE TITLE
Can't build after cocoapods install when use_frameworks is enabled

### ISSUE THREAD

**Issue by benpackard** [ParsePlatform/ParseFacebookUtils-iOS#2]
Install the following Podfile in an otherwise empty project:

```
use_frameworks! 
platform :ios, '8.0'

pod 'ParseFacebookUtilsV4'
```

Xcode reports three compilation errors:

`/Users/benpackard/Cocoa/PodsTest/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginButton.h:21:9: Include of non-modular header inside framework module 'FBSDKLoginKit.FBSDKLoginButton'`

`/Users/benpackard/Cocoa/PodsTest/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginConstants.h:21:9: Include of non-modular header inside framework module 'FBSDKLoginKit.FBSDKLoginConstants'`

`/Users/benpackard/Cocoa/PodsTest/Pods/ParseFacebookUtilsV4/ParseFacebookUtils/Internal/PFFacebookAuthenticationProvider.h:12:9: Could not build module 'FBSDKLoginKit'`

When the `use_frameworks!` option is removed from the Podfile, the project compiles without issue.

**Comment by nlutsenko** [comment]
Hey @benpackard, thanks for the report.
We are aware of this issue and it looks like there is a problem with FBSDKCoreKit/FBSDKLoginKit.
None of the pods (including ParseFacebookUtilsV4) that depend on FBSDKCoreKit+FBSDKLoginKit can build with `use_frameworks!` enabled.

Already followed-up with FBSDK team and they are looking into this problem.
I am also going to look deeper into the problem, but so far - the only workaround is not to `use_frameworks!`. 

More details:
Looks like there is some problem with how imports are managed inside FBSDK kits, where it makes the clang module generation impossible, though on the surface it's not explicit. Due to the fact that modules are disabled for projects that are not using frameworks on Cocoapods - it compiles cleanly when static libraries are used.

**Comment by benpackard** [comment]
Thanks. I will look for another workaround since I have swift pods that require `use_frameworks!`

**Comment by kyle-dinh** [comment]
+1 Please fix

**Comment by sneakersagency** [comment]
Would love a fix for this. :+1:

**Comment by jlalvarez18** [comment]
Please fix :+1:

**Comment by telip007** [comment]
Any solution ?

**Comment by telip007** [comment]
@nlutsenko @benpackard found something ?

**Comment by telip007** [comment]
The workaround doesn't work for me :(

**Comment by nlutsenko** [comment]
After applying the workaround (remove `use_frameworks!` - try deleting `Pods` folder in your project, and rerun `pod install`.

**Comment by benpackard** [comment]
@telip007 no, I have downgraded my version of the Parse SDK for now.

**Comment by manaes** [comment]
Please fix..

**Comment by rmaulsby** [comment]
I am having the same problem when updating to Parse 1.9.0 and ParseFacebookUtilsV4 1.9.0

Downgrading to version 1.8.5, the previous version I had been using, resolves the problem.

**Comment by nlutsenko** [comment]
Hey guys, just wanted to let you know - we are still working with FacebookSDK team on this issue and we should have a new version or updated podspec in the meantime.
One thing that we were able to triage and confirm is that the problem is purely with FBSDKCoreKit+FBSDKLoginKit podspecs at this point, since all pods that depend on those and are installed with `use_frameworks!` are failing to compile.

**Comment by benpackard** [comment]
@nlutsenko Thanks for the update and for pursuing this.

**Comment by willc0de4food** [comment]
@benpackard which versions of the modules should we use in the mean time, while this is being looked into?

**Comment by zeusent** [comment]
But what changed from 1.8.5 to 1.9.0? Is Parse 1.8.5 going to be ok for now?

**Comment by rmaulsby** [comment]
From the Parse team it is a problem with the Facebook SDK, but is
manifesting in 1.9.0.

I am using 1.8.5 without issue

**Comment by telip007** [comment]
@nlutsenko So the problem is not the Facebook SDK, it must be the Parse Facebook Utils, because with Version 1.8.5 and the newest Facebook SDK it works perfect.

**Comment by erikcore** [comment]
The workarounds haven't worked for me and, strangely, even trying to roll back to version 1.8.5 hasn't worked for me. Is there something I'm missing with the workaround? I've cleaned my project and tried deleting my Pods directory and reinstalling.

**Comment by kajensen** [comment]
Any updates? 1.8.5 does not work for me either

**Comment by nlutsenko** [comment]
@telip007, 1.8.5 doesn't compile from source and doesn't import headers from the FBSDKLoginKit - it uses a precompiled binary, that's the reason on why 1.8.5 works and 1.9.0 doesn't.

@erikcore @kajensen 1.8.5 -> 1.9.0 -> 1.8.5 - rough assumptions, since I don't have any context on the errors you guys see:
- Dirty derived data with old artifacts
- Installation of the new version impacted build settings in your project
- Pods folder is dirty
For all of the above - I would suggest simply rolling back in source control.

Once again, any pod that depends on FBSDKLoginKit, and installed via `use_frameworks!` will have the same problem. And we are working to find a solution for this.

Current workaround that resolves the problem: remove `use_frameworks!` from your Podfile.
Sometimes it's not an option if you depend on Swift pods.

FBSDK is fully opensource and if someone wants to attack the problem from their end - I would be more than happy to review the pull request.

**Comment by telip007** [comment]
@nlutsenko hmm ok. Hope that we can find a solution as soon as possible.

**Comment by zeusent** [comment]
@erikcore: Rolling back to 1.8.5 worked for me too. Make sure you roll back both ParseFacebookUtilsV4 & Parse pods to version 1.8.5. At least that's what I did and everything seems to be ok.

**Comment by erikcore** [comment]
@zeusent I ended up rolling everything back to 1.8.5 via source control as suggested above. I was never able to figure out why specifying the earlier versions in my podfile didn't work.

**Comment by kajensen** [comment]
@nlutsenko where can I download 1.8.5? Everything I have done has not worked (rollback, derived data purge, clean, restart, etc). The earliest version in this repo is 1.9.0

**Comment by zeusent** [comment]
You can specify the version you want CocoaPods to install in you Podfile like this:

    pod 'ParseFacebookUtilsV4', '~>1.8.5'

**Comment by kajensen** [comment]
Thanks, I guess I forgot to explicitly state that was what I was doing, which wasn't working. The suggestion was to use source control instead which doesn't work. I would like to manually add it without cocoapods but I cannot find it anywhere

**Comment by telip007** [comment]
@nlutsenko did you find the solution ?

**Comment by jlalvarez18** [comment]
I'm going to personally try to fix this and submit a pull request ASAP. Standby....

**Comment by rmaulsby** [comment]
To specify a specific version use:

pod 'ParseFacebookUtilsV4', '1.8.5'

**Comment by nlutsenko** [comment]
Got tired of waiting for FBSDK guys to fix it and I think I found a solution for this:
Remove `header_dir` setting from FBSDKLoginKit podspec.

It seems to mess with how headers are placed and search paths are resolved.
Guys, try this workaround:

Add/change this line in your Podfile for FBSDKLoginKit:
```
pod 'FBSDKLoginKit', :podspec => 'https://gist.githubusercontent.com/nlutsenko/cf1775dcae07eca6be43/raw/58b919433be07b791dd1036249185b22ecc3de3f/FBSDKLoginKit.podspec'
```

(I just created a [gist](https://gist.github.com/nlutsenko/cf1775dcae07eca6be43) with the updated podspec, here is where the content is coming from)

**Comment by nlutsenko** [comment]
I will update here once again when I have more info, but the workaround works for me locally.
Let me know if it fixes the issue for anyone.

**Comment by jdgong** [comment]
@nlutsenko  Just replace FBSDKLoginKit and leave the others unchanged?

**Comment by nlutsenko** [comment]
Yup. Try it.
Forgot to mention - you would need to rerun pod install.

**Comment by jdgong** [comment]
@nlutsenko It worked. Although it took me a long time to fix all the PFFile optionals.

**Comment by nlutsenko** [comment]
Woohoo! Glad it works. 
Sent the change for a code review, it should be out soon for everyone.

**Comment by telip007** [comment]
Yes works fine! Thank you ;)

**Comment by cashmash** [comment]
when will it be fixed for everyone?

**Comment by nlutsenko** [comment]
Hey guys, the official podspec for FBSDKLoginKit was just updated to `4.7.0.1` which has my fix included.
Please give it a try by running `pod update` and let me know if you run into anything.

**Comment by abrahammstein** [comment]
I just updated to the 4.7.0.1 with 'pod update' but still doesn't work for me :[

**Comment by nlutsenko** [comment]
@abrahammstein, that is sad. Can you share an error log/screenshot here?
Also, try clearing derived data (that is always a good habit).

**Comment by jdgong** [comment]
Error came back after update to xcode 7.1. Neither the 4.7.0.1 nor podspec fix works.

**Comment by nlutsenko** [comment]
Can you post the error? Is it the same one or a different one?
I can't get the error, the solution worked for me and looks like for another person on this thread.

**Comment by jdgong** [comment]
~/Pods/ParseFacebookUtilsV4/ParseFacebookUtils/ParseFacebookUtilsV4.h:10:9: Include of non-modular header inside framework module 'ParseFacebookUtilsV4.ParseFacebookUtilsV4'

~/Pods/ParseFacebookUtilsV4/ParseFacebookUtils/PFFacebookUtils.h:29:1: Duplicate interface definition for class 'PFFacebookUtils'

**Comment by jdgong** [comment]
@nlutsenko just to check is there any update on this issue?

**Comment by Miladinho** [comment]
I read this whole thread. And I realize that I tried to implement Facebook login with parse just today and I am getting the same issues. In other words the workaround isn't working for me. Also, I never had the "use_frameworks!" in my pod file. It's quite aggravating to search the whole web and still have no solution for this.

**Comment by jefflai** [comment]
@nlutsenko @Miladinho @jdgong @benpackard The latest version of ParseFacebookUtilsV4 1.9.0 is working for me now after changing the configuration of my Swift project.  After some trial and error I realized that when you add "use_frameworks!" into the Podfile, some of the Objective-C cocoapods, including Parse and Facebook pods", get imported as modules in Swift.

From my Bridging-Header file, I had to remove

```
#import <Parse/Parse.h>
#import <ParseUI/ParseUI.h>
#import <ParseFacebookUtilsV4/PFFacebookUtils.h>
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import <FBSDKLoginKit/FBSDKLoginKit.h>
```

And then in each of my Swift source code files where I used these libraries, I had to add these imports
```
import Parse
import ParseUI
import ParseFacebookUtilsV4
import FBSDKCoreKit
import FBSDKLoginKit
```
For some reason XCode autocomplete doesn't consistently show the modules, but if you just type in imports and compile it should still work.

Perhaps Parse should add this information into the developer documentation.  I couldn't find this information anywhere online.

**Comment by nlutsenko** [comment]
We have this in Swift Quickstarts actually, but point taken - we should add this to guides as well.

**Comment by jefflai** [comment]
@nlutsenko awesome

**Comment by siavashalipour** [comment]
For anyone having this issue here is my podifle 
```
platform :ios, '9.1' 
use_frameworks!
pod 'Parse'
pod 'FBSDKLoginKit'
pod 'ParseFacebookUtilsV4', '~> 1.9.1'
```

and all the imports work perfectly 
```
import UIKit
import Parse
import Bolts
import FBSDKCoreKit
import ParseFacebookUtilsV4

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
...
```

BTW, I am using Xcode Version 7.1.1 (7B1005) and Swift 2.0

**Comment by Athosone** [comment]
I can't manage to install it:
    <code>FBSDKCoreKit/FBSDKMacros.h file not found.....

Podfile:
  <code>  pod 'Parse'
pod 'FBSDKLoginKit'
pod 'ParseFacebookUtilsV4', '~> 1.9.1'

**Comment by Rom184** [comment]
Same problem @Athosone

**Comment by kajensen** [comment]
add pod 'FBSDKCoreKit'?

**Comment by Athosone** [comment]
it is bound in the FBSDKLoginKit and in the ParseFacebookUtilsV4

**Comment by heramerom** [comment]
I also had the problem.
```
    use_frameworks!
    target 'MyApp' do
        ....
        pod 'FBSDKLoginKit', '~> 4.8.0'
        pod 'FBSDKCoreKit', '~> 4.8.0'
        pod 'FBSDKShareKit', '~> 4.8.0'
        ....
    end
```
It seems that the *FBSDKLoginKit*, *FBSDKShareKit* can not find the *FBSDKCoreKit*, and can not compile.
I don't know why

**Comment by zirinisp** [comment]
I believe this problem is back. Today I did a pod update and i got parse version 1.12.0

After a lot of trial and error I decided to move back to the previous versions and wait for a couple of days until everything is fixed. The following worked for me:

    pod 'Parse', '1.11.0'
    pod 'ParseUI'
    pod 'Bolts'
    pod 'ParseFacebookUtilsV4', '1.9.1'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'

which is my old installation.

**Comment by Athosone** [comment]
With your exact configuration the problem remains,

In fact it do find the header when I replace:
<code>#import \<FBSDKCoreKit/FBSDKMacros.h\> </code>
with:
<code>#import "FBSDKMacros.h" </code>

However I have to do it for all files in FBSDK*Kit ahah... :'(

I have <code>use_frameworks!</code> in my pod also.

**Comment by Athosone** [comment]
any news?

**Comment by nlutsenko** [comment]
Just a quick update: FBSDK v4.9 is coming soon, which has few fixes around this issue.
I'll post a comment here to let you know when it's out, so everyone can retest.

**Comment by crsantos** [comment]
So... Same errors on 4.9.0...

**Comment by Athosone** [comment]
anynews?

**Comment by nlutsenko** [comment]
`4.9.0` shipped last week. Any chance you guys can have this a second go?

**Comment by Athosone** [comment]
Works with 4.9.1 fb sdk ;)!!!!!!!

**Comment by lukecharman** [comment]
Not managed to get this working with the 4.9.1 FB SDK either, still having issues.

**Comment by nlutsenko** [comment]
Hey everyone, going to close this down, since `4.9.1` should resolve the issue here.
@lukecharman, I recommend cleaning Xcode's DerivedData / caches / rebuilding from scratch.
Please open a new issue if you still encounter the problem.

**Comment by bastibense** [comment]
Can confirm this problem is back with the latest 9.10 from Cocoapods on Xcode 7.2.1. 
Apparently Xcode is not able to find the header file `FBSDKMacros.h` even though it's physically on the disk in the Pods directory - so I assume it must have something to do with include paths.

    #import <FBSDKCoreKit/FBSDKMacros.h>

leads to

    Error: 'FBSDKCoreKit/FBSDKMacros.h' file not found

**Comment by markuswinkler** [comment]
Broken on XCode 7.3 beta 5 and 4.10.1
Broken on XCode 7.3 beta 5 and 4.9.1

../Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/FBSDKAppLinkResolver.h:26:10: Include of non-modular header inside framework module 'FBSDKCoreKit.FBSDKAppLinkResolver'
../Pods/ParseFacebookUtilsV4/ParseFacebookUtils/Internal/PFFacebookPrivateUtilities.h:16:9: Could not build module 'FBSDKCoreKit'

Works on XCode 7.2.1, 4.10.1

**Comment by nlutsenko** [comment]
@markuswinkler @bastibense Guys, any chance you can report this via https://developers.facebook.com/bugs/ so we are tracking this against FBSDK, as it looks like there is still a problem there.

**Comment by markuswinkler** [comment]
Filed a bug report, @bastibense feel free to confirm
https://developers.facebook.com/bugs/1573036833024413/

**Comment by nlutsenko** [comment]
@markuswinkler Many thanks! Will investigate into it next week, look for updates on the bug you just filed ;)

**Comment by logicsb** [comment]
to fix this error: 
../Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/FBSDKAppLinkResolver.h:26:10: Include of non-modular header inside framework module 'FBSDKCoreKit.FBSDKAppLinkResolver'
../Pods/ParseFacebookUtilsV4/ParseFacebookUtils/Internal/PFFacebookPrivateUtilities.h:16:9: Could not build module 'FBSDKCoreKit'

on xcode 7.3 i've changed the flag on ParseFacebookUtilsV4 target and works fine :)

![screen shot 2016-03-22 at 3 30 46 am](https://cloud.githubusercontent.com/assets/1790860/13943830/d8063e78-efde-11e5-88fa-92928076eca7.png)

**Comment by mitchellporter** [comment]
@logicsb I've implemented this fix too but unfortunately whenever you run `pod install`, and I'm assuming `pod update` as well, it resets back to `No`.

**Comment by logicsb** [comment]
@mitchellporter Yes :(, but i think that will be fixed in next release :)

**Comment by markuswinkler** [comment]
there is a nice shortcut to it.
![image](https://cloud.githubusercontent.com/assets/762485/14008182/5c65fbc4-f154-11e5-9797-dedbbfe6ac3d.png)
When you get the error (see above) you can click on the yellow framework symbol and this dialogue will show up in the window next to it:
![image](https://cloud.githubusercontent.com/assets/762485/14008194/764817b6-f154-11e5-86cf-0ecd6f608262.png)

**Comment by leorochadel** [comment]
Yesterday I updated Xcode to Version 7.3 (7D175) and suddenly my apps is not building any more. My dead line is near and I can't build the apps :-(

The solution:
I changed the Pods > ParseFacebookUtilsV4 as follow in the image below and everything is fine again. I hope that can help you too.

![screen shot 2016-03-24 at 9 24 06 pm](https://cloud.githubusercontent.com/assets/9798608/14035023/075e7818-f208-11e5-87c0-4dfb81c8f3fe.png)

**Comment by cajun-code** [comment]
I am still running into this.  I am using Xcode 7.3.1 with all the latest and I can't seem to get it to compile.  
This is the error it's giving me. 
> include of non-modular header inside framework module 'FBSDKLoginKit.FBSDKLoginConstants'
> #import <FBSDKCoreKit/FBSDKMacros.h>

Here is the versions of the pods i am running:

> Using Bolts (1.7.0)
> Using FBSDKCoreKit (4.12.0)
> Using FBSDKLoginKit (4.12.0)
> Using MogeanSDK (0.0.3)
> Using Parse (1.13.0)
> Using ParseFacebookUtilsV4 (1.11.1)
> Using SwiftyJSON (2.3.2)

I have this executing at the post instal step.
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DYLIB_COMPATIBILITY_VERSION'] = '500.0.0'
            config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES' 
        end
    end
end
```
Any help would be appreciated.

**Comment by adrianbrink** [comment]
Still happens on the current version, but commenting # use_frameworks! and # platform :ios, '7.0' fixes it.

**Comment by ryanmeisters** [comment]
Fixed for my by updating from FBSDK 4.1.0 to 4.13.1

**Comment by ibrahimkteish** [comment]
I was able to fix this problem by adding `Bolts` framework implicitly in my `Podfile` by adding ` pod 'Bolts', '~> 1.7'`. Note you might have to remove podfile.lock before running `pod install` again

**Comment by leandropjp** [comment]
Still happens on the current version and I need to use use_frameworks! because I am working in Swift.

`source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’
use_frameworks!

target 'SwiftParseChat' do
pod 'Alamofire'
pod 'APAddressBook'
pod 'Bolts’
pod 'JSQMessagesViewController', :git => 'https://github.com/galambalazs/JSQMessagesViewController.git', :branch => ‘develop’
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'JSQSystemSoundPlayer'
pod 'Parse'
pod 'ParseUI'
pod 'ParseFacebookUtilsV4’

end

post_install do |installer|
    `find Pods -regex 'Pods/Parse.*\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)PF\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
    `find Pods -regex 'Pods/Parse.*\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)Parse\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|        configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
end
`

`Installing APAddressBook (0.2.3)
Installing Alamofire (3.5.0)
Installing Bolts (1.8.4)
Installing FBSDKCoreKit (4.15.1)
Installing FBSDKLoginKit (4.15.1)
Installing JSQMessagesViewController (7.1.0)
Installing JSQSystemSoundPlayer (2.0.1)
Installing Parse (1.14.2)
Installing ParseFacebookUtilsV4 (1.11.1)
Installing ParseUI (1.2.0)
`

![image](https://cloud.githubusercontent.com/assets/4974419/18400296/9a77453a-76ab-11e6-920b-1d927eb63485.png)

Any Help?
